Atlt 19 item endopoint
Reckit075/app_to_learn_TS_server pull request #2
Opened 2021-01-16 13:28 UTC by Patrex97

Proszę o code review

2021-01-16 18:01 UTC, Reckit075 reviewed
Tam zostawiłem Ci Patryk notki co moim zdaniem trzeba zmienić.
I może usuń schema usera skoro jest na innym branchu to bezsensu
robic to samo kilka razy bo szkoda czasu.

2021-01-17 17:47 UTC, Patrex97 commented on src/items/items.service.ts
> +      console.error(error);
W odpowiedzi jest zwracana tablica obiektów

2021-01-27 08:25 UTC, rwedzony commented on src/models/user.model.ts
> +export interface UserDto extends mongoose.Document{
Ja jednak byłym zdania, że DTO jest dobre, bo oznacza obiekt przesyłany pomiędzy systemami. Dobrą konwencją jest używanie DTO :)

2021-01-27 12:59 UTC, rwedzony requested changes
z ważnych rzeczy to tylko ten refactor pakietów na ten moment :)

2021-01-27 12:59 UTC, rwedzony commented on src/models/item.model.ts
> +import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
Ja bym Item wrzucił do itemsów i podobnie z userem, żeby wszystko było w odpowiednich pakietach i wywalił w ogóle pakiet "model"

2021-01-27 17:39 UTC, Reckit075 commented on src/models/item.model.ts
> +import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
wiesz co wedlug mnie w models moze to zostac.
Z tego co patrzylem to czesto modele sa w folderze models.

2021-01-27 19:03 UTC, merged